spring:
  application:
    name: APP_GATEWAY
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: lb://ICECREAMPARLOR
          predicates:
            - Path=/inventory/**
        - id: user
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: cart
          uri: lb://TRANSACTION
          predicates:
            - Path=/cart/**
        - id: bill
          uri: lb://TRANSACTION
          predicates:
            - Path=/bill/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
logging:
  level:
    web: debug
server:
  port: 5000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
